spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

logging:
  path: logs/
  level:
      org.springframework.security: DEBUG

server:
  port: 5000

app:
  skeleton:
    validation:
      timeAllow: 5
      enable: false