spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3307/skeleton
    username: admin
    password: aff6afdd
  redis:
    host: 127.0.0.1
    port: 6380

logging:
  path: logs/
  level:
      org.springframework.security: DEBUG

server:
  port: 5000

app:
  skeleton:
    validation:
      timeAllow: 5
      enable: false