spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/skeleton
    username: root
    password: password
  redis:
    host: 127.0.0.1
    port: 6379

logging:
  path: logs/
  level:
      org.springframework.security: DEBUG

server:
  port: 8080

app:
  skeleton:
    validation:
      timeAllow: 5
      enable: true
  auth:
    github:
      clientId: 3517d4ca645a5fc90974
      clientSecret: 5fda54dda689652a75c9dd598c0b8b799dd21228
      accessTokenEndpoint: https://github.com/login/oauth/access_token
      authorizationBaseUrl: https://github.com/login/oauth/authorize
      callBackUrl: http://localhost:8080/oauth/github
      scope: user
      active: true
      verb: post