#By default, use in-memory database for testing
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE;

logging:
  path: logs/

server:
  port: 8080

app:
  skeleton:
    validation:
      timeAllow: 60
      enable: true