spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/skeleton
    username: root
    password: password

logging:
  path: logs/
  level:
      org.springframework.security: DEBUG

server:
  port: 8080

app:
  skeleton:
    validation:
      timeAllow: 5
      enable: false