---
#By default, use in-memory database for testing
spring:
  datasource: 
    url: jdbc:h2:mem:MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE;

---

spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/skeleton
    username: root
    password: password

logging:
  path: logs/
  level:
      org.springframework.security: DEBUG

server:
  port: 8080

app:
  skeleton:
    validation:
      timeAllow: 5
      enable: false
