CREATE TABLE `TRACKER_REQUEST_TIME` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `URI` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `METHOD` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `EXECUTION_TIME` int(11) NOT NULL,
  `UPDATE_TIME` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB;


CREATE TABLE `TRACKER_UNHANDLED_EXCEPTION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EXCEPTION_NAME` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `EXCEPTION_MESSAGE` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `URI` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `METHOD` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `UPDATE_TIME` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

CREATE TABLE `USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(255)  NOT NULL,
  `LAST_NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;